
export enum AlertType {
    CATEGORY_DAILY = 'CATEGORY_DAILY',
    CATEGORY_MONTHLY = 'CATEGORY_MONTHLY',
    DEPARTMENT_MONTHLY = 'DEPARTMENT_MONTHLY',
    MISSING_CONFIGURATION = 'MISSING_CONFIGURATION'
}
